import React from 'react'
import ReactDOM from 'react-dom/client'
import {restaurants} from "./constants/mock.js";

ReactDOM.createRoot(document.getElementById('root')).render(
  <div>
    <h1>Рестораны</h1>
    <ul>
      <li>
        <h2>{restaurants[0].name}</h2>
        <h3>Меню</h3>
        <ul>
          <li>
            <h4>{restaurants[0].menu[0].name}</h4>
            <div>{restaurants[0].menu[0].price}</div>
            <h5>Ингридиенты</h5>
            <ul>
              <li>{restaurants[0].menu[0].ingredients[0]}</li>
              <li>{restaurants[0].menu[0].ingredients[1]}</li>
            </ul>
          </li>
          <li>
            <h4>{restaurants[0].menu[1].name}</h4>
            <div>{restaurants[0].menu[1].price}</div>
            <h5>Ингридиенты</h5>
            <ul>
              <li>{restaurants[0].menu[1].ingredients[0]}</li>
            </ul>
          </li>
          <li>
            <h4>{restaurants[0].menu[2].name}</h4>
            <div>{restaurants[0].menu[2].price}</div>
            <h5>Ингридиенты</h5>
            <ul>
              <li>{restaurants[0].menu[2].ingredients[0]}</li>
              <li>{restaurants[0].menu[2].ingredients[1]}</li>
            </ul>
          </li>
        </ul>
        <h3>Отзывы</h3>
        <ul>
          <li>
            <div>{restaurants[0].reviews[0].text}</div>
            <div>{restaurants[0].reviews[0].user}</div>
            <div>{restaurants[0].reviews[0].rating}</div>
          </li>
          <li>
            <div>{restaurants[0].reviews[1].text}</div>
            <div>{restaurants[0].reviews[1].user}</div>
            <div>{restaurants[0].reviews[1].rating}</div>
          </li>
        </ul>
      </li>
      <li>
        <h2>{restaurants[1].name}</h2>
        <h3>Меню</h3>
        <ul>
          <li>
            <h4>{restaurants[1].menu[0].name}</h4>
            <div>{restaurants[1].menu[0].price}</div>
            <h5>Ингридиенты</h5>
            <ul>
              <li>{restaurants[1].menu[0].ingredients[0]}</li>
              <li>{restaurants[1].menu[0].ingredients[1]}</li>
              <li>{restaurants[1].menu[0].ingredients[2]}</li>
            </ul>
          </li>
          <li>
            <h4>{restaurants[1].menu[1].name}</h4>
            <div>{restaurants[1].menu[1].price}</div>
            <h5>Ингридиенты</h5>
            <ul>
              <li>{restaurants[1].menu[1].ingredients[0]}</li>
              <li>{restaurants[1].menu[1].ingredients[1]}</li>
              <li>{restaurants[1].menu[1].ingredients[2]}</li>
              <li>{restaurants[1].menu[1].ingredients[3]}</li>
            </ul>
          </li>
        </ul>
        <h3>Отзывы</h3>
        <ul>
          <li>
            <div>{restaurants[1].reviews[0].text}</div>
            <div>{restaurants[1].reviews[0].user}</div>
            <div>{restaurants[1].reviews[0].rating}</div>
          </li>
          <li>
            <div>{restaurants[1].reviews[1].text}</div>
            <div>{restaurants[1].reviews[1].user}</div>
            <div>{restaurants[1].reviews[1].rating}</div>
          </li>
          <li>
            <div>{restaurants[1].reviews[2].text}</div>
            <div>{restaurants[1].reviews[2].user}</div>
            <div>{restaurants[1].reviews[2].rating}</div>
          </li>
        </ul>
      </li>
      <li>
        <h2>{restaurants[2].name}</h2>
        <h3>Меню</h3>
        <ul>
          <li>
            <h4>{restaurants[2].menu[0].name}</h4>
            <div>{restaurants[2].menu[0].price}</div>
            <h5>Ингридиенты</h5>
            <ul>
              <li>{restaurants[2].menu[0].ingredients[0]}</li>
            </ul>
          </li>
          <li>
            <h4>{restaurants[2].menu[1].name}</h4>
            <div>{restaurants[2].menu[1].price}</div>
            <h5>Ингридиенты</h5>
            <ul>
              <li>{restaurants[2].menu[1].ingredients[0]}</li>
              <li>{restaurants[2].menu[1].ingredients[1]}</li>
            </ul>
          </li>
          <li>
            <h4>{restaurants[2].menu[2].name}</h4>
            <div>{restaurants[2].menu[2].price}</div>
            <h5>Ингридиенты</h5>
            <ul>
              <li>{restaurants[2].menu[2].ingredients[0]}</li>
            </ul>
          </li>
        </ul>
        <h3>Отзывы</h3>
        <ul>
          <li>
            <div>{restaurants[2].reviews[0].text}</div>
            <div>{restaurants[2].reviews[0].user}</div>
            <div>{restaurants[2].reviews[0].rating}</div>
          </li>
        </ul>
      </li>
      <li>
        <h2>{restaurants[3].name}</h2>
        <h3>Меню</h3>
        <ul>
          <li>
            <h4>{restaurants[3].menu[0].name}</h4>
            <div>{restaurants[3].menu[0].price}</div>
            <h5>Ингридиенты</h5>
            <ul>
              <li>{restaurants[3].menu[0].ingredients[0]}</li>
            </ul>
          </li>
          <li>
            <h4>{restaurants[3].menu[1].name}</h4>
            <div>{restaurants[3].menu[1].price}</div>
            <h5>Ингридиенты</h5>
            <ul>
              <li>{restaurants[3].menu[1].ingredients[0]}</li>
              <li>{restaurants[3].menu[1].ingredients[1]}</li>
            </ul>
          </li>
        </ul>
        <h3>Отзывы</h3>
        <ul>
          <li>
            <div>{restaurants[3].reviews[0].text}</div>
            <div>{restaurants[3].reviews[0].user}</div>
            <div>{restaurants[3].reviews[0].rating}</div>
          </li>
          <li>
            <div>{restaurants[3].reviews[1].text}</div>
            <div>{restaurants[3].reviews[1].user}</div>
            <div>{restaurants[3].reviews[1].rating}</div>
          </li>
        </ul>
      </li>
    </ul>
  </div>
)
